"""Crear tabla enfermeros

Revision ID: 2572b2681f42
Revises: 
Create Date: 2025-10-22 01:59:16.852971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2572b2681f42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enfermeros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('curp', sa.String(length=18), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('cedula_profesional', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('puesto', sa.String(length=50), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('fecha_contratacion', sa.Date(), nullable=False),
    sa.Column('tipo_rotacion', sa.String(length=20), nullable=False),
    sa.Column('supervisor', sa.String(length=100), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('rol_acceso', sa.String(length=20), nullable=False),
    sa.Column('areas_acceso', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula_profesional'),
    sa.UniqueConstraint('curp'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enfermeros')
    # ### end Alembic commands ###
